export const sources = [
  {
    id: "src-iraqi-legal-database",
    title: "قاعدة التشريعات العراقية — مجلس القضاء الأعلى",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-database",
    url: "https://iraqld.e-sjc-services.iq/",
    verificationStatus: "official-service-linked-by-sjc",
    sourceCheckedOn: "2026-07-23",
    accessNote: "خدمة التشريعات المرتبطة من بوابة مجلس القضاء الأعلى؛ قد تعيد منع وصول آلي، لذلك يُحفظ رابط المصدر وتاريخ التحقق."
  },
  {
    id: "src-sjc-article-1126",
    title: "تعليق على قرار محكمة استئناف القادسية بصفتها التمييزية العدد 179/ت-ح/2010",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-commentary",
    url: "https://www.sjc.iq/view.1126/",
    accessNote: "مقال قضائي منشور رسمياً يعرض القرار ويشير إلى اتجاهات تمييزية ذات صلة."
  },
  {
    id: "src-real-estate-law-mirror",
    title: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    publisher: "دليل القوانين العراقية",
    type: "accessible-text-mirror",
    url: "https://www.iraqilaws.com/2024/04/43-1971.html",
    accessNote: "نسخة نصية مساعدة؛ يجب مطابقة النص مع الوقائع العراقية أو قاعدة التشريعات الرسمية عند الاستعمال المهني."
  },
  {
    id: "src-civil-code-mirror",
    title: "القانون المدني العراقي رقم 40 لسنة 1951",
    publisher: "محاميه",
    type: "accessible-text-mirror",
    url: "https://mohamyeh.com/2010/07/04/%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86-%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A-%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82%D9%8A-%D8%B1%D9%82%D9%85-40-%D9%84%D8%B3%D9%86%D8%A9-1951/",
    accessNote: "نسخة نصية مساعدة تذكر بيانات النشر في الوقائع العراقية؛ يلزم التحقق من النسخة النافذة."
  },
  {
    id: "src-iraqi-civil-code-gov-pdf",
    title: "القانون المدني العراقي رقم 40 لسنة 1951 وتعديلاته",
    publisher: "وزارة التجارة العراقية — بوابة تسجيل الشركات",
    type: "official-government-pdf",
    url: "https://tasjeel.mot.gov.iq/newtasjeel/%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86%20%D8%A7%D9%84%D9%85%D8%B3%D8%A7%D9%87%D9%85%D8%A9/%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A%2040%20%D9%84%D8%B3%D9%86%D8%A9%201951.pdf",
    accessNote: "نسخة PDF منشورة على نطاق حكومي عراقي؛ يجب التحقق من النص والنسخة الزمنية الواجبة التطبيق."
  },
  {
    id: "src-sjc-inheritance-article-22",
    title: "تطبيق المادة 22 من القانون المدني على قضايا الميراث",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-commentary",
    url: "https://www.sjc.iq/view.69958/",
    accessNote: "شرح قضائي رسمي لقاعدة الإسناد في المادة 22؛ ليس بديلاً عن نص القانون أو الحكم الكامل."
  },
  {
    id: "src-iraqi-civil-procedure-gov-pdf",
    title: "قانون المرافعات المدنية رقم 83 لسنة 1969",
    publisher: "بوابة الخدمات الحكومية — إقليم كردستان العراق",
    type: "official-government-pdf",
    url: "https://services.gov.krd/sites/default/files/uploaded-laws/%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D9%85%D8%B1%D8%A7%D9%81%D8%B9%D8%A7%D8%AA%20%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A%D8%A9.pdf",
    accessNote: "نسخة PDF منشورة على بوابة حكومية وتتضمن المادة 305؛ يجب مراجعة التعديلات اللاحقة عند الاستعمال المهني."
  },
  {
    id: "src-sjc-qview-719",
    title: "قرار محكمة التمييز الاتحادية 78/صلاحية المحكمة/2007",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.719/",
    accessNote: "نص قرار منشور رسمياً. لا تتضمن صفحة النشر صورة ممسوحة ضوئياً من أصل الحكم."
  },
  {
    id: "src-sjc-study-69972",
    title: "الاستماع لشهادة الشهود في القسام الشرعي أحد وسائل الإثبات",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-guidance",
    url: "https://www.sjc.iq/view.69972/",
    accessNote: "دراسة قضائية رسمية رقم 69/دراسات/2022 مرتبطة بتطبيق المادة 305؛ ليست حكماً قضائياً."
  },
  {
    id: "src-sjc-study-74162",
    title: "التلاعب في القسامات الشرعية",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-guidance",
    url: "https://www.sjc.iq/view.74162/",
    accessNote: "دراسة قضائية رسمية رقم 108/دراسات/2023 عن الاختصاص المكاني بالقسام الشرعي؛ ليست حكماً قضائياً."
  },
  {
    id: "src-sjc-study-69978",
    title: "في حال تعدد صدور القسامات الشرعية لنفس المتوفى فأي قسام يتم اعتماده؟",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-guidance",
    url: "https://www.sjc.iq/view.69978/",
    accessNote: "دراسة قضائية رسمية رقم 109/دراسات/2022 عن معالجة تعدد القسامات؛ ليست حكماً قضائياً."
  },
  {
    id: "src-sjc-qview-3750",
    title: "قرار محكمة التمييز الاتحادية 302/الهيئة الموسعة المدنية/2025",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.3750/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور عن الاختصاص المكاني في الدعاوى العينية العقارية، ومنها إزالة الشيوع."
  },
  {
    id: "src-sjc-qview-2566",
    title: "قرار محكمة التمييز الاتحادية 67/الهيئة الموسعة المدنية/2021",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.2566/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور عن اختصاص محكمة موقع العقار في الدعاوى العينية، ومنها إزالة الشيوع."
  },
  {
    id: "src-sjc-qview-3893",
    title: "قرار محكمة التمييز الاتحادية 1258/الهيئة الاستئنافية عقار/2026",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.3893/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور يميز بين موضوع إزالة الشيوع ومنع المعارضة ويبين متطلبات الإثبات المساحي."
  },
  {
    id: "src-sjc-qview-3837",
    title: "قرار محكمة التمييز الاتحادية 18/الهيئة الموسعة المدنية/2026",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.3837/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور عن استحقاق قيمة المشيدات بعد بيع العقار بالمزايدة في دعوى إزالة الشيوع."
  },
  {
    id: "src-sjc-qview-78",
    title: "قرار محكمة التمييز الاتحادية 1051/العقار المملوك على الشيوع/2006",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.78/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور عن تقدير قيمة البناء الذي أقامه شريك بموافقة بقية الشركاء."
  },
  {
    id: "src-sjc-qview-83",
    title: "قرار محكمة التمييز الاتحادية 1391/إزالة شيوع/2006",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judgment-publication",
    url: "https://www.sjc.iq/qview.83/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "نص قرار رسمي منشور يقرر تقيد المحكمة بطلب القسمة وعدم الحكم بالبيع إذا لم يُطلب."
  },
  {
    id: "src-sjc-study-68047",
    title: "صرف مستحقات إزالة شيوع",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-guidance",
    url: "https://www.sjc.iq/view.68047/",
    verificationStatus: "verified-official",
    sourceCheckedOn: "2026-07-23",
    accessNote: "دراسة قضائية رسمية رقم 65/دراسات/2018 عن إجراءات المزايدة وتوزيع بدل العقار في إزالة الشيوع؛ ليست حكماً قضائياً."
  },
  {
    id: "src-faeez-office-facebook",
    title: "مكتب المحامي فائز الحلي",
    publisher: "مكتب المحامي فائز الحلي",
    type: "secondary-legal-commentary-publisher",
    platform: "Facebook",
    url: "https://www.facebook.com/faeezoffice/",
    providedUrl: "https://www.facebook.com/share/1HPQc1YcFf/?mibextid=wwXIfr",
    verificationStatus: "publisher-identity-verified",
    rightsPolicy: "link-and-cite-only-unless-reuse-permission",
    imagePolicy: "لا تُخزن أو يُعاد نشر صورة القرار من الصفحة إلا بعد التحقق من مصدرها وحق إعادة استخدامها؛ وإلا يُكتفى بالرابط والإسناد.",
    accessNote: "صفحة عامة تنشر قرارات قضائية وشروحاً قانونية. تُعامل منشوراتها كنقل أو تعليق قانوني ثانوي، ويجب مطابقة رقم القرار وتاريخه ونصه مع المصدر الرسمي متى توفر."
  }
];

export const laws = [
  {
    id: "irq-constitution-2005",
    country: "العراق",
    title: "دستور جمهورية العراق",
    number: null,
    year: 2005,
    category: "دستوري",
    status: "نافذ مع وجوب التحقق من أي تعديل لاحق",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-civil-code-40-1951",
    country: "العراق",
    title: "القانون المدني العراقي",
    number: 40,
    year: 1951,
    category: "مدني",
    status: "نافذ ومعدل — تحقق من النسخة النافذة بتاريخ الواقعة",
    gazette: "الوقائع العراقية، العدد 3015، 8 أيلول 1951، ص 243",
    sourceIds: ["src-iraqi-legal-database", "src-iraqi-civil-code-gov-pdf", "src-sjc-inheritance-article-22", "src-civil-code-mirror"],
    articles: [
      {
        number: "22",
        text: "قضايا الميراث يسري عليها قانون المورث وقت موته مع مراعاة ما يلي: أ- اختلاف الجنسية غير مانع من الإرث في الأموال المنقولة والعقارات، غير أن العراقي لا يرثه من الأجانب إلا من كان قانون دولته يورث العراقي منه. ب- الأجنبي الذي لا وارث له تؤول أمواله التي في العراق للدولة العراقية ولو صرح قانون دولته بخلاف ذلك.",
        verification: "نص مُراجع على نسخة حكومية وشرح قضائي رسمي؛ يحدد القانون الموضوعي للميراث ولا يحدد المحكمة المختصة بإصدار القسام الشرعي."
      },
      {
        number: "1106",
        text: "1- يكسب الوارث بطريق الميراث المنقولات والعقارات والحقوق الموجودة في التركة. 2- وتعيين الورثة وتحديد أنصبائهم في الإرث وانتقال أموال التركة، تسري عليها أحكام الشريعة الإسلامية والقوانين الخاصة بها.",
        verification: "نص مُراجع على النسخة النصية المشار إليها؛ يلزم التحقق من المصدر الرسمي عند الاستعمال القضائي."
      }
    ]
  },
  {
    id: "irq-penal-code-111-1969",
    country: "العراق",
    title: "قانون العقوبات العراقي",
    number: 111,
    year: 1969,
    category: "جزائي",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-civil-procedure-83-1969",
    country: "العراق",
    title: "قانون المرافعات المدنية",
    number: 83,
    year: 1969,
    category: "مرافعات",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database", "src-iraqi-civil-procedure-gov-pdf"],
    articles: [
      {
        number: "305",
        text: "1- تختص محكمة محل إقامة المتوفى الدائمي بإصدار القسام الشرعي ولا يعتد بالقسامات الشرعية الصادرة من محكمة أخرى. 2- وتختص اختصاصاً مكانياً محكمة إقامة المتوفى الدائم ومحكمة محل التركة بتحرير التركة. 3- تجرى تصفية التركة في محل إقامة المتوفى الدائم مع مراعاة اختصاصات المحاكم الأخرى بشأن ما لديها من أموال المتوفى طبقاً لما هو منصوص عليه في قانون إدارة أموال القاصرين.",
        verification: "نص مُراجع على المادة 305 في نسخة PDF حكومية. الفقرة الأولى تنظم اختصاص إصدار القسام الشرعي؛ ولا تُغني بذاتها عن قواعد تنازع القوانين أو الاعتراف بالأحكام الأجنبية.",
        primarySourceIds: ["src-iraqi-civil-procedure-gov-pdf"],
        verificationStatus: "source-checked",
        verificationTier: "official-copy",
        sourceCheckedOn: "2026-07-22",
        consolidationStatus: "amendments-not-fully-consolidated",
        effectiveDateStatus: "verify-at-relevant-date",
        editorialNotes: [
          "تمت مطابقة النص مع نسخة PDF منشورة على بوابة حكومية.",
          "لا تمثل هذه البطاقة ضماناً بأن جميع التعديلات حتى تاريخ واقعة معينة مدخلة."
        ]
      }
    ]
  },
  {
    id: "irq-evidence-107-1979",
    country: "العراق",
    title: "قانون الإثبات",
    number: 107,
    year: 1979,
    category: "إثبات",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-personal-status-188-1959",
    country: "العراق",
    title: "قانون الأحوال الشخصية",
    number: 188,
    year: 1959,
    category: "أحوال شخصية",
    status: "نافذ ومعدل — يلزم تحديد النص الواجب التطبيق",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-foreigners-residence-76-2017",
    country: "العراق",
    title: "قانون إقامة الأجانب",
    number: 76,
    year: 2017,
    category: "إقامة وأجانب",
    status: "يلزم التحقق من النسخة النافذة والتعليمات",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-enforcement-45-1980",
    country: "العراق",
    title: "قانون التنفيذ",
    number: 45,
    year: 1980,
    category: "تنفيذ",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-real-estate-registration-43-1971",
    country: "العراق",
    title: "قانون التسجيل العقاري",
    number: 43,
    year: 1971,
    category: "تسجيل عقاري",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database", "src-real-estate-law-mirror"],
    articles: [
      {
        number: "3/2",
        text: "لا ينعقد التصرف العقاري إلا بالتسجيل في دائرة التسجيل العقاري.",
        verification: "نص مُراجع على النسخة النصية المشار إليها."
      },
      {
        number: "4",
        text: "لا يجوز إجراء التصرفات العقارية على الحقوق التي صدر بها حكم قضائي حائز على درجة البتات أو قرار قانوني له قوة الحكم القضائي إلا بعد تسجيل تلك الحقوق في السجل العقاري.",
        verification: "نص مُراجع على النسخة النصية المشار إليها."
      },
      {
        number: "189",
        text: "يكتسب الوارث حق الملكية العقارية وما في حكمها من تاريخ وفاة المورث غير أنه لا يمكنه التصرف به إلا بعد تسجيله في السجل العقاري.",
        verification: "نص مُراجع على مصدر قضائي رسمي ونسخة نصية مساعدة."
      }
    ]
  }
];

export const cases = [
  {
    id: "case-qadisiyah-179-2010",
    title: "ملكية الوارث للعقار قبل التسجيل",
    country: "العراق",
    topic: "الإرث والتسجيل العقاري",
    courtType: "بداءة/استئناف بصفتها التمييزية",
    isSynthetic: false,
    dataQuality: "ملخص منشور رسمياً؛ وقائع قرار البداءة غير معروضة بالكامل",
    decisionIds: ["dec-qadisiyah-179-2010"]
  },
  {
    id: "case-cassation-jurisdiction-78-2007",
    title: "اختصاص القسام الشرعي وحدود امتداده إلى حجة الوصاية",
    country: "العراق",
    topic: "القسام الشرعي وحجة الوصاية",
    courtType: "أحوال شخصية/تمييز اتحادي",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً؛ أُخفيت أسماء الأطراف في العرض، ولا توجد صورة أصلية للحكم في صفحة النشر.",
    decisionIds: ["dec-cassation-jurisdiction-78-2007"]
  },
  {
    id: "case-coownership-jurisdiction-302-2025",
    title: "الاختصاص المكاني في دعوى إزالة الشيوع",
    country: "العراق",
    topic: "إزالة الشيوع والاختصاص المكاني",
    courtType: "تمييز اتحادي/هيئة موسعة مدنية",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-jurisdiction-302-2025"]
  },
  {
    id: "case-coownership-jurisdiction-67-2021",
    title: "محكمة موقع العقار في دعوى إزالة الشيوع",
    country: "العراق",
    topic: "إزالة الشيوع والاختصاص المكاني",
    courtType: "تمييز اتحادي/هيئة موسعة مدنية",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-jurisdiction-67-2021"]
  },
  {
    id: "case-coownership-evidence-1258-2026",
    title: "حدود الاستناد إلى كشف إزالة الشيوع في دعوى منع المعارضة",
    country: "العراق",
    topic: "إزالة الشيوع والإثبات في منع المعارضة",
    courtType: "تمييز اتحادي/هيئة استئنافية عقار",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-evidence-1258-2026"]
  },
  {
    id: "case-coownership-constructions-18-2026",
    title: "قيمة المشيدات بعد بيع العقار لإزالة الشيوع",
    country: "العراق",
    topic: "إزالة الشيوع وحقوق صاحب المشيدات",
    courtType: "تمييز اتحادي/هيئة موسعة مدنية",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-constructions-18-2026"]
  },
  {
    id: "case-coownership-constructions-1051-2006",
    title: "تقدير قيمة بناء الشريك المقام بموافقة الشركاء",
    country: "العراق",
    topic: "إزالة الشيوع والعقار المملوك على الشيوع",
    courtType: "تمييز اتحادي",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-constructions-1051-2006"]
  },
  {
    id: "case-coownership-relief-1391-2006",
    title: "تقيد المحكمة بطلب القسمة في دعوى إزالة الشيوع",
    country: "العراق",
    topic: "إزالة الشيوع ونطاق عريضة الدعوى",
    courtType: "تمييز اتحادي",
    isSynthetic: false,
    dataQuality: "نص قرار منشور رسمياً على موقع مجلس القضاء الأعلى",
    decisionIds: ["dec-coownership-relief-1391-2006"]
  },
  {
    id: "case-demo-unregistered-heir-a",
    title: "الحجز التنفيذي على حصة إرثية غير مسجلة — المسار أ",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف/تمييز/تصحيح",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية صُممت لعرض وظائف التطبيق ولا تمثل دعوى أو قراراً حقيقياً",
    decisionIds: [
      "demo-a-trial",
      "demo-a-appeal",
      "demo-a-cassation",
      "demo-a-correction"
    ]
  },
  {
    id: "case-demo-unregistered-heir-b",
    title: "الحجز التنفيذي على حصة إرثية غير مسجلة — المسار ب",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف/تمييز",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية صُممت لإظهار اختلاف اجتهادي محتمل ولا تمثل دعوى أو قراراً حقيقياً",
    decisionIds: ["demo-b-trial", "demo-b-appeal", "demo-b-cassation"]
  },
  {
    id: "case-demo-registered-heir",
    title: "الحجز على حصة إرثية مسجلة باسم المدين",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية لاختبار أثر اختلاف واقعة التسجيل",
    decisionIds: ["demo-c-trial", "demo-c-appeal"]
  }
];

function officialJudgmentAssets(url) {
  return [
    {
      type: "official-web-publication",
      url,
      mimeType: "text/html",
      label: "النص الرسمي المنشور للقرار",
      rightsStatus: "public-official-copy",
      availability: "available",
      isOriginalDecisionImage: false
    }
  ];
}

export const decisions = [
  {
    id: "dec-qadisiyah-179-2010",
    caseId: "case-qadisiyah-179-2010",
    displayNumber: "179/ت-ح/2010",
    date: "2010-11-29",
    year: 2010,
    court: "محكمة استئناف القادسية بصفتها التمييزية",
    courtLevel: "استئناف بصفتها التمييزية",
    stage: "تمييز",
    stageOrder: 3,
    title: "اكتساب الوارث ملكية العقار من تاريخ الوفاة وقيد التصرف قبل التسجيل",
    issue: "أثر عدم تسجيل حق الإرث في السجل العقاري على تصرف الوارث",
    factSummary: "المصدر المنشور لم يعرض وقائع حكم البداءة كاملة؛ واستند القرار إلى اكتساب الوارث الملكية بالميراث مع منعه من التصرف قبل التسجيل.",
    reasoningSummary: "استند إلى المادة 1106 من القانون المدني والمادة 189 من قانون التسجيل العقاري.",
    outcome: "تصديق القرار المميز ورد العريضة التمييزية",
    outcomeCode: "restrict-disposition-before-registration",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["إرث", "عقار", "تسجيل", "تصرف الوارث"],
    factTags: ["حق إرث غير موضح التسجيل", "وقائع ناقصة"],
    registrationStatus: "غير محسوم من النص المنشور",
    proceduralPosture: "طعن تمييزي في قرار بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary"
  },
  {
    id: "dec-cassation-jurisdiction-78-2007",
    caseId: "case-cassation-jurisdiction-78-2007",
    displayNumber: "78/صلاحية المحكمة/2007",
    date: "2007-11-22",
    year: 2007,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "قيد الاختصاص المكاني للقسام الشرعي لا يمتد إلى حجة الوصاية",
    issue: "هل يمتد اختصاص محكمة محل إقامة المتوفى الدائم الوارد للمحكمة المختصة بالقسام الشرعي إلى إصدار حجة الوصاية؟",
    factSummary: "يتعلق الطعن بحجة وصاية أصدرتها محكمة أحوال شخصية خارج محل إقامة المتوفى الدائم. يعرض التطبيق الوقائع بأسماء غير حقيقية ولا يعيد نشر بيانات شخصية من صفحة القرار.",
    reasoningSummary: "قيد الاختصاص المكاني في المادة 305 يخص إصدار القسام الشرعي؛ أما حجة الوصاية فلا يشملها هذا القيد، فيجوز إصدارها من محكمة أحوال شخصية أخرى متى توافرت شروطها.",
    outcome: "تصديق النتيجة ورد الاعتراضات التمييزية وتحميل المميز رسم التمييز",
    outcomeCode: "guardianship-order-outside-qasam-jurisdiction",
    lawArticles: ["irq-civil-procedure-83-1969:305"],
    issueTags: ["قسام شرعي", "اختصاص مكاني", "حجة وصاية", "أحوال شخصية"],
    factTags: ["محكمة خارج محل الإقامة", "حجة وصاية", "قسام شرعي"],
    registrationStatus: "غير منطبق",
    proceduralPosture: "طعن تمييزي في حجة وصاية",
    lawVersion: "قانون المرافعات المدنية رقم 83 لسنة 1969 المعدل",
    factCompleteness: "medium",
    sourceIds: ["src-sjc-qview-719"],
    sourceUrl: "https://www.sjc.iq/qview.719/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-text",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "تظهر صفحة النشر الرسمية ترقيم مادة محتملاً الخطأ في موضع من النص؛ رُبط القرار بالمادة 305 موضوعياً، ويجب مراجعة صورة الحكم أو الأضبارة قبل الاستعمال القضائي.",
      "صفحة النشر الرسمية تعرض نصاً إلكترونياً ولا تنشر صورة الحكم الأصلية."
    ],
    documentAssets: [
      {
        type: "official-web-publication",
        url: "https://www.sjc.iq/qview.719/",
        mimeType: "text/html",
        label: "النص الرسمي المنشور للقرار",
        rightsStatus: "public-official-copy",
        availability: "available",
        isOriginalDecisionImage: false
      },
      {
        type: "official-scan",
        url: null,
        mimeType: null,
        label: "صورة الحكم الأصلية",
        rightsStatus: "linked-only",
        availability: "not-published",
        isOriginalDecisionImage: true
      }
    ]
  },
  {
    id: "dec-coownership-jurisdiction-302-2025",
    caseId: "case-coownership-jurisdiction-302-2025",
    displayNumber: "302/الهيئة الموسعة المدنية/2025",
    date: "2025-12-09",
    year: 2025,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "اختصاص محكمة موقع العقار بالدعاوى العينية العقارية",
    issue: "تعيين المحكمة المختصة مكانياً بالدعوى العينية العقارية، مع ذكر إزالة الشيوع ضمن أمثلتها",
    factSummary: "نشأ تنازع سلبي في الاختصاص بين محكمتي بداءة بشأن دعوى تتعلق بنقل ملكية عقار. يعرض التطبيق الأطراف دون أسماء حقيقية، ولا يعيد نشر أي بيانات شخصية.",
    reasoningSummary: "قرر النص الرسمي أن الدعاوى العينية العقارية، ومنها إزالة الشيوع وإلغاء التسجيل ونقل الملكية، تقام أمام محكمة البداءة التي يقع العقار ضمن اختصاصها المكاني وفق المادة 36 من قانون المرافعات المدنية.",
    outcome: "تعيين محكمة بداءة الشعب محكمة مختصة بنظر الدعوى وإرسال الإضبارة إليها",
    outcomeCode: "clarify-in-rem-property-jurisdiction",
    lawArticles: [],
    issueTags: ["إزالة الشيوع", "اختصاص مكاني", "دعوى عينية عقارية", "محكمة موقع العقار"],
    factTags: ["تنازع سلبي في الاختصاص", "نقل ملكية عقار", "الأطراف محجوبة في العرض"],
    registrationStatus: "غير منطبق",
    proceduralPosture: "حسم تنازع سلبي في الاختصاص",
    lawVersion: "قانون المرافعات المدنية العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "medium",
    sourceIds: ["src-sjc-qview-3750"],
    sourceUrl: "https://www.sjc.iq/qview.3750/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-text",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "موضوع الدعوى الأصلية نقل ملكية عقار، وقد أورد القرار إزالة الشيوع مثالاً صريحاً للدعوى العينية العقارية.",
      "لا تُعامل هذه الخلاصة بديلاً عن قراءة النص الرسمي الكامل."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.3750/")
  },
  {
    id: "dec-coownership-jurisdiction-67-2021",
    caseId: "case-coownership-jurisdiction-67-2021",
    displayNumber: "67/الهيئة الموسعة المدنية/2021",
    date: "2021-02-08",
    year: 2021,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "تمييز دعوى إزالة الشيوع العينية عن دعوى رفع التجاوز",
    issue: "حدود قاعدة اختصاص محكمة موقع العقار والتمييز بين الدعوى العينية ودعوى رفع التجاوز",
    factSummary: "تعلقت الدعوى الأصلية برفع تجاوز، ثم ظهر نزاع بين محكمتي بداءة حول المحكمة المختصة. يعرض التطبيق الوقائع بأسماء محجوبة.",
    reasoningSummary: "بيّن النص الرسمي أن المادة 36 تشمل الدعاوى العينية مثل إزالة الشيوع وإلغاء التسجيل ونقل الملكية، بينما لا تعد دعوى رفع التجاوز من تلك الدعاوى، ولا تنقل إلى محكمة أخرى من دون دفع المدعى عليه بعدم الاختصاص.",
    outcome: "إعادة الإضبارة إلى محكمة بداءة الزهور للسير فيها",
    outcomeCode: "distinguish-in-rem-from-encroachment-jurisdiction",
    lawArticles: [],
    issueTags: ["إزالة الشيوع", "رفع التجاوز", "اختصاص مكاني", "دعوى عينية"],
    factTags: ["تنازع اختصاص", "دعوى رفع تجاوز", "الأطراف محجوبة في العرض"],
    registrationStatus: "غير منطبق",
    proceduralPosture: "حسم تنازع في الاختصاص بين محكمتي بداءة",
    lawVersion: "قانون المرافعات المدنية العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "medium",
    sourceIds: ["src-sjc-qview-2566"],
    sourceUrl: "https://www.sjc.iq/qview.2566/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-text",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "هذا القرار مفيد بوصفه حالة تمييز إجرائي؛ فموضوعه الأصلي رفع التجاوز وليس إزالة الشيوع."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.2566/")
  },
  {
    id: "dec-coownership-evidence-1258-2026",
    caseId: "case-coownership-evidence-1258-2026",
    displayNumber: "1258/الهيئة الاستئنافية عقار/2026",
    date: "2026-04-12",
    year: 2026,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "عدم كفاية كشف إزالة الشيوع لإثبات منع المعارضة",
    issue: "هل يصلح كشف سابق في دعوى إزالة الشيوع دليلاً على واقعة الغصب أو الانتفاع في دعوى منع المعارضة؟",
    factSummary: "استند أحد الخصوم في دعوى منع معارضة إلى تقرير كشف من مسار إزالة شيوع سابق، بينما تختلف المسألتان في محل الإثبات.",
    reasoningSummary: "يفصل المبدأ المنشور بين إثبات الملكية أو أوصاف العقار في إزالة الشيوع وبين إثبات وضع اليد والانتفاع في منع المعارضة، ويوجب الاستناد إلى الخرائط الرسمية والتحقيق المساحي الملائم للدعوى.",
    outcome: "نقض الحكم المميز وإعادة الإضبارة لاستكمال الإثبات وفق الخرائط الرسمية والخبرة المساحية الملائمة",
    outcomeCode: "reverse-and-remand-for-official-survey-evidence",
    lawArticles: [],
    issueTags: ["إزالة الشيوع", "منع المعارضة", "إثبات", "كشف", "خرائط رسمية"],
    factTags: ["تقرير كشف سابق", "اختلاف محل الإثبات", "الأطراف محجوبة في العرض"],
    registrationStatus: "غير محدد",
    proceduralPosture: "طعن تمييزي عقاري",
    lawVersion: "القانون العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "low",
    sourceIds: ["src-sjc-qview-3893"],
    sourceUrl: "https://www.sjc.iq/qview.3893/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-text",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "نص القرار الرسمي يذكر صراحة نقض الحكم المميز وإعادة الإضبارة إلى محكمتها."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.3893/")
  },
  {
    id: "dec-coownership-constructions-18-2026",
    caseId: "case-coownership-constructions-18-2026",
    displayNumber: "18/الهيئة الموسعة المدنية/2026",
    date: "2026-01-21",
    year: 2026,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "استحقاق قيمة المشيدات بعد بيع العقار لإزالة الشيوع",
    issue: "حق الشريك الذي أنشأ مشيدات من ماله في قيمتها بعد بيع العقار بالمزايدة",
    factSummary: "أنشأ أحد الشركاء مشيدات من ماله، ولم يطالب بقية الشركاء بإزالتها قبل بيع العقار في دعوى إزالة الشيوع. بيع العقار وأحيل نهائياً على منشئ المشيدات، وتسلم بقية الشركاء حصصهم من بدل البيع.",
    reasoningSummary: "اعتبر النص الرسمي أن سكوت الشركاء عن طلب إزالة المشيدات قبل المزايدة، مع ثبوت إنشائها من مال الشريك، يساند استحقاقه لقيمتها من حصيلة المزايدة.",
    outcome: "تصديق الحكم ورد الطعن التمييزي",
    outcomeCode: "allow-construction-value-after-auction",
    lawArticles: [],
    issueTags: ["إزالة الشيوع", "مشيدات", "مزايدة", "حقوق الشريك"],
    factTags: ["بناء من مال الشريك", "عدم طلب الإزالة قبل البيع", "إحالة نهائية", "الأطراف محجوبة في العرض"],
    registrationStatus: "بيع بالمزايدة في مسار إزالة الشيوع",
    proceduralPosture: "طعن تمييزي في حكم مدني بعد المزايدة",
    lawVersion: "القانون العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "medium",
    sourceIds: ["src-sjc-qview-3837"],
    sourceUrl: "https://www.sjc.iq/qview.3837/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-text",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "يشير القرار إلى المادة 210/2 من قانون المرافعات؛ لم تُضمّن المادة في متن القاعدة قبل التحقق من نسخة رسمية محدثة."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.3837/")
  },
  {
    id: "dec-coownership-constructions-1051-2006",
    caseId: "case-coownership-constructions-1051-2006",
    displayNumber: "1051/العقار المملوك على الشيوع/2006",
    date: "2006-08-24",
    year: 2006,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "تقدير قيمة بناء الشريك المقام بموافقة بقية الشركاء",
    issue: "زمن تقدير قيمة البناء الذي يقيمه شريك بموافقة الشركاء الآخرين",
    factSummary: "يعرض المصدر الرسمي مبدأً عن شريك أقام بناءً في عقار مملوك على الشيوع بموافقة بقية الشركاء؛ تفاصيل الوقائع الكاملة غير مضمنة في الملخص.",
    reasoningSummary: "يقضي المبدأ الرسمي المنشور باستحقاق الشريك قيمة البناء وقت إنشائه عند ثبوت موافقة بقية الشركاء.",
    outcome: "اعتماد استحقاق قيمة البناء وقت الإنشاء عند تحقق الموافقة",
    outcomeCode: "allow-construction-value-at-building-time",
    lawArticles: [],
    issueTags: ["عقار على الشيوع", "بناء الشريك", "موافقة الشركاء", "تقدير القيمة"],
    factTags: ["وقائع منشورة على هيئة مبدأ", "الأطراف محجوبة في العرض"],
    registrationStatus: "غير محدد",
    proceduralPosture: "تمييز عقاري",
    lawVersion: "القانون العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "low",
    sourceIds: ["src-sjc-qview-78"],
    sourceUrl: "https://www.sjc.iq/qview.78/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-publication",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "صفحة المصدر الرسمية قد تمنع القراءة الآلية بصورة متقطعة؛ يجب فتح الرابط ومراجعة النص عند الاستعمال المهني."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.78/")
  },
  {
    id: "dec-coownership-relief-1391-2006",
    caseId: "case-coownership-relief-1391-2006",
    displayNumber: "1391/إزالة شيوع/2006",
    date: "2006-08-27",
    year: 2006,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "تقيد المحكمة بطلب القسمة وعدم الحكم بالبيع من تلقاء نفسها",
    issue: "حدود سلطة المحكمة عندما يطلب المدعي قسمة العقار دون طلب بيعه",
    factSummary: "تعلق المبدأ المنشور بعريضة اقتصرت على طلب قسمة العقار الشائع، بينما اتجه الحكم إلى البيع.",
    reasoningSummary: "قرر المبدأ الرسمي أن المحكمة تتقيد بطلبات عريضة الدعوى، فلا تحكم ببيع العقار إذا اقتصر الطلب على القسمة.",
    outcome: "عدم جواز الحكم بالبيع عند اقتصار الطلب على القسمة",
    outcomeCode: "restrict-relief-to-partition-request",
    lawArticles: [],
    issueTags: ["إزالة الشيوع", "عريضة الدعوى", "القسمة", "البيع", "نطاق الطلبات"],
    factTags: ["طلب قسمة فقط", "حكم بالبيع", "الأطراف محجوبة في العرض"],
    registrationStatus: "غير محدد",
    proceduralPosture: "تمييز حكم إزالة شيوع",
    lawVersion: "القانون العراقي النافذ بتاريخ القرار — يلزم التحقق من النسخة المطبقة عند الاستعمال المهني",
    factCompleteness: "low",
    sourceIds: ["src-sjc-qview-83"],
    sourceUrl: "https://www.sjc.iq/qview.83/",
    isSynthetic: false,
    publicationType: "judgment",
    verification: "verified-official-publication",
    sourceQuality: "official-judgment-publication",
    editorialNotes: [
      "صفحة المصدر الرسمية قد تمنع القراءة الآلية بصورة متقطعة؛ يجب فتح الرابط ومراجعة النص عند الاستعمال المهني."
    ],
    documentAssets: officialJudgmentAssets("https://www.sjc.iq/qview.83/")
  },
  {
    id: "dec-federal-1386-2006",
    caseId: null,
    displayNumber: "1386/مدنية عقار/2006",
    date: "2006-07-25",
    year: 2006,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "قرار تمييزي مشار إليه بشأن قراءة المادة 189 تسجيل عقاري",
    issue: "مدى حصر المنع الوارد في المادة 189 بالتصرفات التي تستلزم التسجيل",
    factSummary: "أشير إلى القرار في تعليق قضائي رسمي بوصفه تطبيقاً لاتجاه يميز بين نشوء الحق وإمكان تسجيل التصرف؛ النص الكامل للقرار غير مضمن في بيانات النسخة التجريبية.",
    reasoningSummary: "الاتجاه المنشور في التعليق يقرأ التسجيل كاشفاً لحق الإرث ويقصر أثر المنع على التسجيل العقاري، مع وجوب مراجعة القرار الكامل قبل الاعتماد المهني.",
    outcome: "اتجاه يسمح بحماية الحق مع تأخير التسجيل إلى حين تسجيل الانتقال",
    outcomeCode: "right-exists-registration-deferred",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["إرث", "عقار", "تسجيل", "أثر كاشف"],
    factTags: ["نص القرار الكامل غير متاح", "قرار مشار إليه"],
    registrationStatus: "غير مسجل وقت نشوء الحق وفق ملخص التعليق",
    proceduralPosture: "تمييز مدني عقار",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary-citation"
  },
  {
    id: "dec-federal-689-2010",
    caseId: null,
    displayNumber: "689/مدنية عقار/2010",
    date: "2010-09-05",
    year: 2010,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "قرار تمييزي مشار إليه بشأن أثر التسجيل في التصرف العقاري",
    issue: "عدم ترتيب التصرف العقاري أثره العيني قبل التسجيل",
    factSummary: "أشير إلى القرار في تعليق قضائي رسمي ضمن شرح اشتراط التسجيل للتصرفات العقارية؛ النص الكامل غير مضمن في النسخة التجريبية.",
    reasoningSummary: "التصرف العقاري لا يرتب الأثر العيني المقصود قبل استكمال التسجيل وفق القواعد الخاصة.",
    outcome: "تأكيد مركزية التسجيل للتصرف العقاري",
    outcomeCode: "registration-required-for-real-right-effect",
    lawArticles: ["irq-real-estate-registration-43-1971:3/2", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["عقار", "تسجيل", "تصرف عقاري"],
    factTags: ["نص القرار الكامل غير متاح", "قرار مشار إليه"],
    registrationStatus: "غير محدد",
    proceduralPosture: "تمييز مدني عقار",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary-citation"
  },
  {
    id: "demo-a-trial",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/بداءة",
    date: "2026-03-02",
    year: 2026,
    court: "محكمة بداءة افتراضية",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "رفض الحجز على حصة إرثية غير مسجلة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار ما زال مسجلاً باسم المورث، والمدين وارث لم يسجل حق الانتقال باسمه، وطلب الدائن الحجز على حصة منسوبة إليه.",
    reasoningSummary: "تعذر تعيين الحق في السجل باسم المدين، مع التمييز بين اكتساب الإرث وإمكان إجراء التصرف أو التأشير العقاري.",
    outcome: "رفض طلب الحجز",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "طلب منع معارضة الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-appeal",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/استئناف",
    date: "2026-04-10",
    year: 2026,
    court: "محكمة استئناف افتراضية",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد رفض الحجز على الحصة غير المسجلة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "ذات وقائع قرار البداءة: لا يوجد قيد عقاري باسم المدين الوارث.",
    reasoningSummary: "الحجز التنفيذي يحتاج مالاً قابلاً للتعيين والتنفيذ في السجل، ولم يثبت قيد الحصة باسم المدين.",
    outcome: "تأييد الحكم البدائي",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-cassation",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/تمييز",
    date: "2026-05-17",
    year: 2026,
    court: "محكمة تمييز افتراضية",
    courtLevel: "تمييز",
    stage: "تمييز",
    stageOrder: 3,
    title: "نقض الحكم واعتبار الملكية مكتسبة بالوفاة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والمدين وارث لم يسجل الحصة باسمه.",
    reasoningSummary: "اكتساب الملكية يقع من تاريخ الوفاة؛ ورأت الهيئة التجريبية أن الحجز إجراء تحفظي لا يعد تصرفاً ناقلاً للملكية.",
    outcome: "نقض الحكم وإعادة الدعوى",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "تمييز حكم استئنافي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    correctedBy: "demo-a-correction",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-correction",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/تصحيح",
    date: "2026-06-04",
    year: 2026,
    court: "محكمة تمييز افتراضية — هيئة تصحيح",
    courtLevel: "تمييز",
    stage: "تصحيح القرار التمييزي",
    stageOrder: 4,
    title: "تصحيح القرار التمييزي وتثبيت تعذر الحجز قبل التسجيل",
    issue: "أثر المادة 189 في قابلية الحصة الإرثية غير المسجلة للحجز التنفيذي",
    factSummary: "الحصة لم تسجل باسم المدين، ولا توجد صحيفة عقارية شخصية تثبت مقدارها على نحو قابل للتأشير.",
    reasoningSummary: "فرّق القرار التجريبي بين اكتساب الملكية حكماً وبين قابلية الحق للتعيين والتأشير في السجل لأغراض التنفيذ.",
    outcome: "تصحيح القرار ورد الطعن وتأييد رفض الحجز",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل", "تصحيح قرار تمييزي"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "طلب تصحيح قرار تمييزي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    corrects: "demo-a-cassation",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-trial",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/بداءة",
    date: "2026-02-11",
    year: 2026,
    court: "محكمة بداءة افتراضية أخرى",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "السماح بالحجز استناداً إلى انتقال الملكية بالوفاة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والمدين وارث وحصته محددة بقسام شرعي لكنها غير مسجلة عقارياً.",
    reasoningSummary: "اعتبر الحكم التجريبي أن الملكية تنتقل بالوفاة وأن الحجز لا يمثل تصرفاً إرادياً من الوارث.",
    outcome: "رد الاعتراض على الحجز",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "اعتراض على الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-appeal",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/استئناف",
    date: "2026-03-15",
    year: 2026,
    court: "محكمة استئناف افتراضية أخرى",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد السماح بالحجز على الحصة الإرثية",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث والحصة غير مسجلة باسم المدين الوارث.",
    reasoningSummary: "الحجز لا ينقل الملكية فوراً، والملكية الإرثية مكتسبة من تاريخ الوفاة وفق القراءة التجريبية.",
    outcome: "تأييد رد الاعتراض",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-cassation",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/تمييز",
    date: "2026-05-01",
    year: 2026,
    court: "محكمة تمييز افتراضية أخرى",
    courtLevel: "تمييز",
    stage: "تمييز",
    stageOrder: 3,
    title: "تأييد اتجاه السماح بالحجز قبل تسجيل الانتقال",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والحصة غير مسجلة باسم المدين الوارث.",
    reasoningSummary: "الملكية الإرثية تنتقل بالوفاة، واعتبر القرار التجريبي الحجز وسيلة تنفيذ لا تصرفاً عقارياً إرادياً.",
    outcome: "رد الطعن وتأييد الحجز",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "تمييز حكم استئنافي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-c-trial",
    caseId: "case-demo-registered-heir",
    displayNumber: "DEMO-C/بداءة",
    date: "2026-01-20",
    year: 2026,
    court: "محكمة بداءة افتراضية",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "السماح بالحجز على حصة مسجلة باسم المدين",
    issue: "جواز الحجز التنفيذي على حصة إرثية مسجلة",
    factSummary: "سُجل انتقال الإرث وحددت حصة المدين في السجل العقاري قبل طلب الحجز.",
    reasoningSummary: "زالت عقبة عدم التسجيل وأصبح الحق معيناً في السجل باسم المدين.",
    outcome: "رد الاعتراض على الحجز",
    outcomeCode: "allow-seizure-registered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["الحصة مسجلة", "المدين مالك مقيد"],
    registrationStatus: "مسجل باسم المدين",
    proceduralPosture: "اعتراض على الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-c-appeal",
    caseId: "case-demo-registered-heir",
    displayNumber: "DEMO-C/استئناف",
    date: "2026-02-28",
    year: 2026,
    court: "محكمة استئناف افتراضية",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد الحجز لثبوت التسجيل باسم المدين",
    issue: "جواز الحجز التنفيذي على حصة إرثية مسجلة",
    factSummary: "الحصة محددة ومسجلة باسم المدين قبل الحجز.",
    reasoningSummary: "أصبح الحق قابلاً للتعيين والتأشير التنفيذي في السجل العقاري.",
    outcome: "تأييد الحكم البدائي",
    outcomeCode: "allow-seizure-registered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["الحصة مسجلة", "المدين مالك مقيد"],
    registrationStatus: "مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  }
];

export const legalAuthorities = [
  {
    id: "authority-sjc-69-2022",
    title: "الاستماع لشهادة الشهود في القسام الشرعي أحد وسائل الإثبات",
    number: "69/دراسات/2022",
    date: "2022-08-18",
    publicationType: "judicial-guidance",
    issuer: "مجلس القضاء الأعلى العراقي",
    summary: "توضح الدراسة القضائية الرسمية أن شهادة الشهود تظل من وسائل الإثبات المهمة عند إصدار القسام الشرعي، في سياق تطبيق المادة 305 من قانون المرافعات المدنية.",
    lawArticles: ["irq-civil-procedure-83-1969:305"],
    sourceIds: ["src-sjc-study-69972"],
    verification: "official-guidance",
    documentAssets: [
      {
        type: "official-web-publication",
        url: "https://www.sjc.iq/view.69972/",
        mimeType: "text/html",
        label: "الدراسة القضائية الرسمية المنشورة",
        rightsStatus: "public-official-copy",
        availability: "available",
        isOriginalDecisionImage: false
      }
    ]
  },
  {
    id: "authority-sjc-108-2023",
    title: "التلاعب في القسامات الشرعية",
    number: "108/دراسات/2023",
    date: "2024-07-11",
    publicationType: "judicial-guidance",
    issuer: "مجلس القضاء الأعلى العراقي",
    summary: "تقرر الدراسة القضائية الرسمية أن القسام الشرعي الصادر من محكمة محل الإقامة الدائم للمتوفى هو الذي يُعتمد، وأن القسام الصادر من محكمة أخرى لا يُعوّل عليه، وفق ضابط الاختصاص في المادة 305.",
    lawArticles: ["irq-civil-procedure-83-1969:305"],
    sourceIds: ["src-sjc-study-74162"],
    verification: "official-guidance",
    documentAssets: [
      {
        type: "official-web-publication",
        url: "https://www.sjc.iq/view.74162/",
        mimeType: "text/html",
        label: "الدراسة القضائية الرسمية المنشورة",
        rightsStatus: "public-official-copy",
        availability: "available",
        isOriginalDecisionImage: false
      }
    ]
  },
  {
    id: "authority-sjc-109-2022",
    title: "في حال تعدد صدور القسامات الشرعية لنفس المتوفى فأي قسام يتم اعتماده؟",
    number: "109/دراسات/2022",
    date: "2022-08-18",
    publicationType: "judicial-guidance",
    issuer: "مجلس القضاء الأعلى العراقي",
    summary: "توضح الدراسة أنه عند تعدد القسامات الشرعية لنفس المتوفى تُوقف المعاملة، ويُكلّف صاحب المصلحة بمراجعة المحكمة المختصة للطعن أو إبطال أحد القسامات قبل اعتماد القسام الصحيح.",
    lawArticles: ["irq-civil-procedure-83-1969:305"],
    sourceIds: ["src-sjc-study-69978"],
    verification: "official-guidance",
    documentAssets: [
      {
        type: "official-web-publication",
        url: "https://www.sjc.iq/view.69978/",
        mimeType: "text/html",
        label: "الدراسة القضائية الرسمية المنشورة",
        rightsStatus: "public-official-copy",
        availability: "available",
        isOriginalDecisionImage: false
      }
    ]
  },
  {
    id: "authority-sjc-65-2018",
    title: "صرف مستحقات إزالة الشيوع",
    number: "65/دراسات/2018",
    date: "2021-02-23",
    publicationType: "judicial-guidance",
    issuer: "مجلس القضاء الأعلى العراقي",
    summary: "تشرح الدراسة القضائية الرسمية الإطار الموضوعي والإجرائي لإزالة الشيوع، من حق الشريك في طلب الخروج من الشيوع والقسمة أو البيع عند تعذرها، إلى إجراءات الكشف والمزايدة وتوزيع البدل وفق قانون التنفيذ.",
    lawArticles: [],
    sourceIds: ["src-sjc-study-68047"],
    verification: "official-guidance",
    editorialNotes: [
      "ورد في صفحة الدراسة رقم غير صحيح للقانون المدني؛ لا يعتمد المشروع هذا الرقم، ويعامل القانون المدني العراقي بوصفه القانون رقم 40 لسنة 1951."
    ],
    documentAssets: [
      {
        type: "official-web-publication",
        url: "https://www.sjc.iq/view.68047/",
        mimeType: "text/html",
        label: "الدراسة القضائية الرسمية المنشورة",
        rightsStatus: "public-official-copy",
        availability: "available",
        isOriginalDecisionImage: false
      }
    ]
  }
];

export const projectMetadata = {
  nameAr: "المحامي",
  nameEn: "Al-Muhami",
  taglineAr: "بحث قانوني عراقي موثّق ومقارنة شفافة للاتجاهات القضائية",
  version: "0.7.0",
  jurisdiction: "العراق",
  corpusNotice: "نسخة بحثية أولية: تتضمن تشريعات مختارة، وأحكاماً رسمية مختارة في إزالة الشيوع مرتبطة بالنص المنشور، وقرارات أخرى بملخصات مصدرية، وبيانات تجريبية موسومة بوضوح لاختبار وظائف مسار الدعوى والمقارنة.",
  legalNotice: "مساعد بحث قانوني وليس بديلاً عن المحامي أو المحكمة. يجب مراجعة النص الرسمي الكامل والنسخة النافذة قبل أي استعمال مهني أو قضائي."
};
