export const sources = [
  {
    id: "src-iraqi-legal-database",
    title: "قاعدة التشريعات العراقية — مجلس القضاء الأعلى",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-database",
    url: "https://iraqld.hjc.iq/",
    accessNote: "المصدر الرسمي المرجعي للتشريعات العراقية؛ قد يفرض الموقع قيود وصول آلية."
  },
  {
    id: "src-sjc-article-1126",
    title: "تعليق على قرار محكمة استئناف القادسية بصفتها التمييزية العدد 179/ت-ح/2010",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-commentary",
    url: "https://www.sjc.iq/view.1126/",
    accessNote: "مقال قضائي منشور رسمياً يعرض القرار ويشير إلى اتجاهات تمييزية ذات صلة."
  },
  {
    id: "src-real-estate-law-mirror",
    title: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    publisher: "دليل القوانين العراقية",
    type: "accessible-text-mirror",
    url: "https://www.iraqilaws.com/2024/04/43-1971.html",
    accessNote: "نسخة نصية مساعدة؛ يجب مطابقة النص مع الوقائع العراقية أو قاعدة التشريعات الرسمية عند الاستعمال المهني."
  },
  {
    id: "src-civil-code-mirror",
    title: "القانون المدني العراقي رقم 40 لسنة 1951",
    publisher: "محاميه",
    type: "accessible-text-mirror",
    url: "https://mohamyeh.com/2010/07/04/%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86-%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A-%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82%D9%8A-%D8%B1%D9%82%D9%85-40-%D9%84%D8%B3%D9%86%D8%A9-1951/",
    accessNote: "نسخة نصية مساعدة تذكر بيانات النشر في الوقائع العراقية؛ يلزم التحقق من النسخة النافذة."
  },
  {
    id: "src-iraqi-civil-code-gov-pdf",
    title: "القانون المدني العراقي رقم 40 لسنة 1951 وتعديلاته",
    publisher: "وزارة التجارة العراقية — بوابة تسجيل الشركات",
    type: "official-government-pdf",
    url: "https://tasjeel.mot.gov.iq/newtasjeel/%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86%20%D8%A7%D9%84%D9%85%D8%B3%D8%A7%D9%87%D9%85%D8%A9/%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A%2040%20%D9%84%D8%B3%D9%86%D8%A9%201951.pdf",
    accessNote: "نسخة PDF منشورة على نطاق حكومي عراقي؛ يجب التحقق من النص والنسخة الزمنية الواجبة التطبيق."
  },
  {
    id: "src-sjc-inheritance-article-22",
    title: "تطبيق المادة 22 من القانون المدني على قضايا الميراث",
    publisher: "مجلس القضاء الأعلى العراقي",
    type: "official-judicial-commentary",
    url: "https://www.sjc.iq/view.69958/",
    accessNote: "شرح قضائي رسمي لقاعدة الإسناد في المادة 22؛ ليس بديلاً عن نص القانون أو الحكم الكامل."
  },
  {
    id: "src-iraqi-civil-procedure-gov-pdf",
    title: "قانون المرافعات المدنية رقم 83 لسنة 1969",
    publisher: "بوابة الخدمات الحكومية — إقليم كردستان العراق",
    type: "official-government-pdf",
    url: "https://services.gov.krd/sites/default/files/uploaded-laws/%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D9%85%D8%B1%D8%A7%D9%81%D8%B9%D8%A7%D8%AA%20%D8%A7%D9%84%D9%85%D8%AF%D9%86%D9%8A%D8%A9.pdf",
    accessNote: "نسخة PDF منشورة على بوابة حكومية وتتضمن المادة 305؛ يجب مراجعة التعديلات اللاحقة عند الاستعمال المهني."
  }
];

export const laws = [
  {
    id: "irq-constitution-2005",
    country: "العراق",
    title: "دستور جمهورية العراق",
    number: null,
    year: 2005,
    category: "دستوري",
    status: "نافذ مع وجوب التحقق من أي تعديل لاحق",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-civil-code-40-1951",
    country: "العراق",
    title: "القانون المدني العراقي",
    number: 40,
    year: 1951,
    category: "مدني",
    status: "نافذ ومعدل — تحقق من النسخة النافذة بتاريخ الواقعة",
    gazette: "الوقائع العراقية، العدد 3015، 8 أيلول 1951، ص 243",
    sourceIds: ["src-iraqi-legal-database", "src-iraqi-civil-code-gov-pdf", "src-sjc-inheritance-article-22", "src-civil-code-mirror"],
    articles: [
      {
        number: "22",
        text: "قضايا الميراث يسري عليها قانون المورث وقت موته مع مراعاة ما يلي: أ- اختلاف الجنسية غير مانع من الإرث في الأموال المنقولة والعقارات، غير أن العراقي لا يرثه من الأجانب إلا من كان قانون دولته يورث العراقي منه. ب- الأجنبي الذي لا وارث له تؤول أمواله التي في العراق للدولة العراقية ولو صرح قانون دولته بخلاف ذلك.",
        verification: "نص مُراجع على نسخة حكومية وشرح قضائي رسمي؛ يحدد القانون الموضوعي للميراث ولا يحدد المحكمة المختصة بإصدار القسام الشرعي."
      },
      {
        number: "1106",
        text: "1- يكسب الوارث بطريق الميراث المنقولات والعقارات والحقوق الموجودة في التركة. 2- وتعيين الورثة وتحديد أنصبائهم في الإرث وانتقال أموال التركة، تسري عليها أحكام الشريعة الإسلامية والقوانين الخاصة بها.",
        verification: "نص مُراجع على النسخة النصية المشار إليها؛ يلزم التحقق من المصدر الرسمي عند الاستعمال القضائي."
      }
    ]
  },
  {
    id: "irq-penal-code-111-1969",
    country: "العراق",
    title: "قانون العقوبات العراقي",
    number: 111,
    year: 1969,
    category: "جزائي",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-civil-procedure-83-1969",
    country: "العراق",
    title: "قانون المرافعات المدنية",
    number: 83,
    year: 1969,
    category: "مرافعات",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database", "src-iraqi-civil-procedure-gov-pdf"],
    articles: [
      {
        number: "305",
        text: "1- تختص محكمة محل إقامة المتوفى الدائمي بإصدار القسام الشرعي ولا يعتد بالقسامات الشرعية الصادرة من محكمة أخرى. 2- وتختص اختصاصاً مكانياً محكمة إقامة المتوفى الدائم ومحكمة محل التركة بتحرير التركة. 3- تجرى تصفية التركة في محل إقامة المتوفى الدائم مع مراعاة اختصاصات المحاكم الأخرى بشأن ما لديها من أموال المتوفى طبقاً لما هو منصوص عليه في قانون إدارة أموال القاصرين.",
        verification: "نص مُراجع على المادة 305 في نسخة PDF حكومية. الفقرة الأولى تنظم اختصاص إصدار القسام الشرعي؛ ولا تُغني بذاتها عن قواعد تنازع القوانين أو الاعتراف بالأحكام الأجنبية."
      }
    ]
  },
  {
    id: "irq-evidence-107-1979",
    country: "العراق",
    title: "قانون الإثبات",
    number: 107,
    year: 1979,
    category: "إثبات",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-personal-status-188-1959",
    country: "العراق",
    title: "قانون الأحوال الشخصية",
    number: 188,
    year: 1959,
    category: "أحوال شخصية",
    status: "نافذ ومعدل — يلزم تحديد النص الواجب التطبيق",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-foreigners-residence-76-2017",
    country: "العراق",
    title: "قانون إقامة الأجانب",
    number: 76,
    year: 2017,
    category: "إقامة وأجانب",
    status: "يلزم التحقق من النسخة النافذة والتعليمات",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-enforcement-45-1980",
    country: "العراق",
    title: "قانون التنفيذ",
    number: 45,
    year: 1980,
    category: "تنفيذ",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database"],
    articles: []
  },
  {
    id: "irq-real-estate-registration-43-1971",
    country: "العراق",
    title: "قانون التسجيل العقاري",
    number: 43,
    year: 1971,
    category: "تسجيل عقاري",
    status: "نافذ ومعدل — يلزم التحقق من النسخة النافذة",
    sourceIds: ["src-iraqi-legal-database", "src-real-estate-law-mirror"],
    articles: [
      {
        number: "3/2",
        text: "لا ينعقد التصرف العقاري إلا بالتسجيل في دائرة التسجيل العقاري.",
        verification: "نص مُراجع على النسخة النصية المشار إليها."
      },
      {
        number: "4",
        text: "لا يجوز إجراء التصرفات العقارية على الحقوق التي صدر بها حكم قضائي حائز على درجة البتات أو قرار قانوني له قوة الحكم القضائي إلا بعد تسجيل تلك الحقوق في السجل العقاري.",
        verification: "نص مُراجع على النسخة النصية المشار إليها."
      },
      {
        number: "189",
        text: "يكتسب الوارث حق الملكية العقارية وما في حكمها من تاريخ وفاة المورث غير أنه لا يمكنه التصرف به إلا بعد تسجيله في السجل العقاري.",
        verification: "نص مُراجع على مصدر قضائي رسمي ونسخة نصية مساعدة."
      }
    ]
  }
];

export const cases = [
  {
    id: "case-qadisiyah-179-2010",
    title: "ملكية الوارث للعقار قبل التسجيل",
    country: "العراق",
    topic: "الإرث والتسجيل العقاري",
    courtType: "بداءة/استئناف بصفتها التمييزية",
    isSynthetic: false,
    dataQuality: "ملخص منشور رسمياً؛ وقائع قرار البداءة غير معروضة بالكامل",
    decisionIds: ["dec-qadisiyah-179-2010"]
  },
  {
    id: "case-demo-unregistered-heir-a",
    title: "الحجز التنفيذي على حصة إرثية غير مسجلة — المسار أ",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف/تمييز/تصحيح",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية صُممت لعرض وظائف التطبيق ولا تمثل دعوى أو قراراً حقيقياً",
    decisionIds: [
      "demo-a-trial",
      "demo-a-appeal",
      "demo-a-cassation",
      "demo-a-correction"
    ]
  },
  {
    id: "case-demo-unregistered-heir-b",
    title: "الحجز التنفيذي على حصة إرثية غير مسجلة — المسار ب",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف/تمييز",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية صُممت لإظهار اختلاف اجتهادي محتمل ولا تمثل دعوى أو قراراً حقيقياً",
    decisionIds: ["demo-b-trial", "demo-b-appeal", "demo-b-cassation"]
  },
  {
    id: "case-demo-registered-heir",
    title: "الحجز على حصة إرثية مسجلة باسم المدين",
    country: "العراق",
    topic: "الحجز التنفيذي والتسجيل العقاري",
    courtType: "بداءة/استئناف",
    isSynthetic: true,
    dataQuality: "بيانات افتراضية لاختبار أثر اختلاف واقعة التسجيل",
    decisionIds: ["demo-c-trial", "demo-c-appeal"]
  }
];

export const decisions = [
  {
    id: "dec-qadisiyah-179-2010",
    caseId: "case-qadisiyah-179-2010",
    displayNumber: "179/ت-ح/2010",
    date: "2010-11-29",
    year: 2010,
    court: "محكمة استئناف القادسية بصفتها التمييزية",
    courtLevel: "استئناف بصفتها التمييزية",
    stage: "تمييز",
    stageOrder: 3,
    title: "اكتساب الوارث ملكية العقار من تاريخ الوفاة وقيد التصرف قبل التسجيل",
    issue: "أثر عدم تسجيل حق الإرث في السجل العقاري على تصرف الوارث",
    factSummary: "المصدر المنشور لم يعرض وقائع حكم البداءة كاملة؛ واستند القرار إلى اكتساب الوارث الملكية بالميراث مع منعه من التصرف قبل التسجيل.",
    reasoningSummary: "استند إلى المادة 1106 من القانون المدني والمادة 189 من قانون التسجيل العقاري.",
    outcome: "تصديق القرار المميز ورد العريضة التمييزية",
    outcomeCode: "restrict-disposition-before-registration",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["إرث", "عقار", "تسجيل", "تصرف الوارث"],
    factTags: ["حق إرث غير موضح التسجيل", "وقائع ناقصة"],
    registrationStatus: "غير محسوم من النص المنشور",
    proceduralPosture: "طعن تمييزي في قرار بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary"
  },
  {
    id: "dec-federal-1386-2006",
    caseId: null,
    displayNumber: "1386/مدنية عقار/2006",
    date: "2006-07-25",
    year: 2006,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "قرار تمييزي مشار إليه بشأن قراءة المادة 189 تسجيل عقاري",
    issue: "مدى حصر المنع الوارد في المادة 189 بالتصرفات التي تستلزم التسجيل",
    factSummary: "أشير إلى القرار في تعليق قضائي رسمي بوصفه تطبيقاً لاتجاه يميز بين نشوء الحق وإمكان تسجيل التصرف؛ النص الكامل للقرار غير مضمن في بيانات النسخة التجريبية.",
    reasoningSummary: "الاتجاه المنشور في التعليق يقرأ التسجيل كاشفاً لحق الإرث ويقصر أثر المنع على التسجيل العقاري، مع وجوب مراجعة القرار الكامل قبل الاعتماد المهني.",
    outcome: "اتجاه يسمح بحماية الحق مع تأخير التسجيل إلى حين تسجيل الانتقال",
    outcomeCode: "right-exists-registration-deferred",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["إرث", "عقار", "تسجيل", "أثر كاشف"],
    factTags: ["نص القرار الكامل غير متاح", "قرار مشار إليه"],
    registrationStatus: "غير مسجل وقت نشوء الحق وفق ملخص التعليق",
    proceduralPosture: "تمييز مدني عقار",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary-citation"
  },
  {
    id: "dec-federal-689-2010",
    caseId: null,
    displayNumber: "689/مدنية عقار/2010",
    date: "2010-09-05",
    year: 2010,
    court: "محكمة التمييز الاتحادية",
    courtLevel: "تمييز اتحادي",
    stage: "تمييز",
    stageOrder: 3,
    title: "قرار تمييزي مشار إليه بشأن أثر التسجيل في التصرف العقاري",
    issue: "عدم ترتيب التصرف العقاري أثره العيني قبل التسجيل",
    factSummary: "أشير إلى القرار في تعليق قضائي رسمي ضمن شرح اشتراط التسجيل للتصرفات العقارية؛ النص الكامل غير مضمن في النسخة التجريبية.",
    reasoningSummary: "التصرف العقاري لا يرتب الأثر العيني المقصود قبل استكمال التسجيل وفق القواعد الخاصة.",
    outcome: "تأكيد مركزية التسجيل للتصرف العقاري",
    outcomeCode: "registration-required-for-real-right-effect",
    lawArticles: ["irq-real-estate-registration-43-1971:3/2", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["عقار", "تسجيل", "تصرف عقاري"],
    factTags: ["نص القرار الكامل غير متاح", "قرار مشار إليه"],
    registrationStatus: "غير محدد",
    proceduralPosture: "تمييز مدني عقار",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "low",
    sourceIds: ["src-sjc-article-1126"],
    sourceUrl: "https://www.sjc.iq/view.1126/",
    isSynthetic: false,
    sourceQuality: "official-commentary-citation"
  },
  {
    id: "demo-a-trial",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/بداءة",
    date: "2026-03-02",
    year: 2026,
    court: "محكمة بداءة افتراضية",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "رفض الحجز على حصة إرثية غير مسجلة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار ما زال مسجلاً باسم المورث، والمدين وارث لم يسجل حق الانتقال باسمه، وطلب الدائن الحجز على حصة منسوبة إليه.",
    reasoningSummary: "تعذر تعيين الحق في السجل باسم المدين، مع التمييز بين اكتساب الإرث وإمكان إجراء التصرف أو التأشير العقاري.",
    outcome: "رفض طلب الحجز",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "طلب منع معارضة الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-appeal",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/استئناف",
    date: "2026-04-10",
    year: 2026,
    court: "محكمة استئناف افتراضية",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد رفض الحجز على الحصة غير المسجلة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "ذات وقائع قرار البداءة: لا يوجد قيد عقاري باسم المدين الوارث.",
    reasoningSummary: "الحجز التنفيذي يحتاج مالاً قابلاً للتعيين والتنفيذ في السجل، ولم يثبت قيد الحصة باسم المدين.",
    outcome: "تأييد الحكم البدائي",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-cassation",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/تمييز",
    date: "2026-05-17",
    year: 2026,
    court: "محكمة تمييز افتراضية",
    courtLevel: "تمييز",
    stage: "تمييز",
    stageOrder: 3,
    title: "نقض الحكم واعتبار الملكية مكتسبة بالوفاة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والمدين وارث لم يسجل الحصة باسمه.",
    reasoningSummary: "اكتساب الملكية يقع من تاريخ الوفاة؛ ورأت الهيئة التجريبية أن الحجز إجراء تحفظي لا يعد تصرفاً ناقلاً للملكية.",
    outcome: "نقض الحكم وإعادة الدعوى",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "تمييز حكم استئنافي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    correctedBy: "demo-a-correction",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-a-correction",
    caseId: "case-demo-unregistered-heir-a",
    displayNumber: "DEMO-A/تصحيح",
    date: "2026-06-04",
    year: 2026,
    court: "محكمة تمييز افتراضية — هيئة تصحيح",
    courtLevel: "تمييز",
    stage: "تصحيح القرار التمييزي",
    stageOrder: 4,
    title: "تصحيح القرار التمييزي وتثبيت تعذر الحجز قبل التسجيل",
    issue: "أثر المادة 189 في قابلية الحصة الإرثية غير المسجلة للحجز التنفيذي",
    factSummary: "الحصة لم تسجل باسم المدين، ولا توجد صحيفة عقارية شخصية تثبت مقدارها على نحو قابل للتأشير.",
    reasoningSummary: "فرّق القرار التجريبي بين اكتساب الملكية حكماً وبين قابلية الحق للتعيين والتأشير في السجل لأغراض التنفيذ.",
    outcome: "تصحيح القرار ورد الطعن وتأييد رفض الحجز",
    outcomeCode: "deny-seizure-unregistered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل", "تصحيح قرار تمييزي"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "طلب تصحيح قرار تمييزي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    corrects: "demo-a-cassation",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-trial",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/بداءة",
    date: "2026-02-11",
    year: 2026,
    court: "محكمة بداءة افتراضية أخرى",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "السماح بالحجز استناداً إلى انتقال الملكية بالوفاة",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والمدين وارث وحصته محددة بقسام شرعي لكنها غير مسجلة عقارياً.",
    reasoningSummary: "اعتبر الحكم التجريبي أن الملكية تنتقل بالوفاة وأن الحجز لا يمثل تصرفاً إرادياً من الوارث.",
    outcome: "رد الاعتراض على الحجز",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "اعتراض على الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-appeal",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/استئناف",
    date: "2026-03-15",
    year: 2026,
    court: "محكمة استئناف افتراضية أخرى",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد السماح بالحجز على الحصة الإرثية",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث والحصة غير مسجلة باسم المدين الوارث.",
    reasoningSummary: "الحجز لا ينقل الملكية فوراً، والملكية الإرثية مكتسبة من تاريخ الوفاة وفق القراءة التجريبية.",
    outcome: "تأييد رد الاعتراض",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-b-cassation",
    caseId: "case-demo-unregistered-heir-b",
    displayNumber: "DEMO-B/تمييز",
    date: "2026-05-01",
    year: 2026,
    court: "محكمة تمييز افتراضية أخرى",
    courtLevel: "تمييز",
    stage: "تمييز",
    stageOrder: 3,
    title: "تأييد اتجاه السماح بالحجز قبل تسجيل الانتقال",
    issue: "جواز الحجز التنفيذي على حصة إرثية لم تسجل باسم المدين",
    factSummary: "العقار باسم المورث، والحصة غير مسجلة باسم المدين الوارث.",
    reasoningSummary: "الملكية الإرثية تنتقل بالوفاة، واعتبر القرار التجريبي الحجز وسيلة تنفيذ لا تصرفاً عقارياً إرادياً.",
    outcome: "رد الطعن وتأييد الحجز",
    outcomeCode: "allow-seizure-unregistered-share",
    lawArticles: ["irq-civil-code-40-1951:1106", "irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["العقار باسم المورث", "الحصة غير مسجلة", "المدين وارث"],
    registrationStatus: "غير مسجل باسم المدين",
    proceduralPosture: "تمييز حكم استئنافي",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-c-trial",
    caseId: "case-demo-registered-heir",
    displayNumber: "DEMO-C/بداءة",
    date: "2026-01-20",
    year: 2026,
    court: "محكمة بداءة افتراضية",
    courtLevel: "بداءة",
    stage: "بداءة",
    stageOrder: 1,
    title: "السماح بالحجز على حصة مسجلة باسم المدين",
    issue: "جواز الحجز التنفيذي على حصة إرثية مسجلة",
    factSummary: "سُجل انتقال الإرث وحددت حصة المدين في السجل العقاري قبل طلب الحجز.",
    reasoningSummary: "زالت عقبة عدم التسجيل وأصبح الحق معيناً في السجل باسم المدين.",
    outcome: "رد الاعتراض على الحجز",
    outcomeCode: "allow-seizure-registered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["الحصة مسجلة", "المدين مالك مقيد"],
    registrationStatus: "مسجل باسم المدين",
    proceduralPosture: "اعتراض على الحجز",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  },
  {
    id: "demo-c-appeal",
    caseId: "case-demo-registered-heir",
    displayNumber: "DEMO-C/استئناف",
    date: "2026-02-28",
    year: 2026,
    court: "محكمة استئناف افتراضية",
    courtLevel: "استئناف",
    stage: "استئناف",
    stageOrder: 2,
    title: "تأييد الحجز لثبوت التسجيل باسم المدين",
    issue: "جواز الحجز التنفيذي على حصة إرثية مسجلة",
    factSummary: "الحصة محددة ومسجلة باسم المدين قبل الحجز.",
    reasoningSummary: "أصبح الحق قابلاً للتعيين والتأشير التنفيذي في السجل العقاري.",
    outcome: "تأييد الحكم البدائي",
    outcomeCode: "allow-seizure-registered-share",
    lawArticles: ["irq-real-estate-registration-43-1971:189"],
    issueTags: ["حجز تنفيذي", "إرث", "عقار", "تسجيل"],
    factTags: ["الحصة مسجلة", "المدين مالك مقيد"],
    registrationStatus: "مسجل باسم المدين",
    proceduralPosture: "استئناف حكم بداءة",
    lawVersion: "قانون التسجيل العقاري رقم 43 لسنة 1971 المعدل",
    factCompleteness: "high",
    sourceIds: [],
    sourceUrl: "",
    isSynthetic: true,
    sourceQuality: "synthetic-demo"
  }
];

export const projectMetadata = {
  nameAr: "المحامي",
  nameEn: "Al-Muhami",
  taglineAr: "بحث قانوني عراقي موثّق ومقارنة شفافة للاتجاهات القضائية",
  version: "0.4.0",
  jurisdiction: "العراق",
  corpusNotice: "نسخة بحثية أولية: تتضمن تشريعات مختارة، قرارات منشورة بملخصات مصدرية، وبيانات تجريبية موسومة بوضوح لاختبار وظائف مسار الدعوى والمقارنة.",
  legalNotice: "مساعد بحث قانوني وليس بديلاً عن المحامي أو المحكمة. يجب مراجعة النص الرسمي الكامل والنسخة النافذة قبل أي استعمال مهني أو قضائي."
};
